# Generated by Django 3.2.5 on 2022-07-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.TextField()),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StructTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_nr', models.IntegerField()),
                ('use_gene_info', models.BooleanField()),
                ('use_grn_info', models.BooleanField()),
                ('use_struct_info', models.BooleanField()),
                ('selection_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protos.testuser')),
            ],
        ),
    ]
